### ISSUE TITLE
COPYING.txt

### ISSUE THREAD

**Issue by egcpvanloon** [TRIQS/ctseg_J#11]
### Description

There is no COPYING.txt in the top-level directory, even though LICENSE.txt states that it should be there.

**Comment by HugoStrand** [comment]
Please consider fixing this since it is a requirement of the pending JOSS manuscript review, see openjournals/joss-reviews#7425.

See TPRF for an example, https://github.com/TRIQS/tprf/blob/3.3.x/COPYING.txt

Best, Hugo

**Comment by nkavokine** [comment]
Thank you for pointing this out! Problem fixed now.
