### ISSUE TITLE
Documentation: chemical potential and Hartree shifts

### ISSUE THREAD

**Issue by egcpvanloon** [TRIQS/ctseg_J#12]
Interactions generate Hartree shifts which can be accounted for by shifting the chemical potential. For a single-orbital model with static interactions and particle-hole symmetric hybridization function, it is well-known that mu=U/2 gives half-filling, and this is usually the scenario that new users start with. 

Retarded interactions also generate similar Hartree shifts. I think it would be useful to explicitly write in the documentation how to get to half-filling for particle-hole symmetric models. For example, for the density-density interaction, the required shift is given by U(i\omega_n=0). This would be beneficial for new users.

**Comment by nkavokine** [comment]
Thank you for this good suggestion. I have now added to the documentation a paragraph on how to achieve half-filling: https://triqs.github.io/ctseg/latest/guide/step_by_step.html#conditions-for-half-filling
